### ISSUE TITLE
GetTeamDriveOrganizers.py - Error on Get ACLs for all Team Drives

### ISSUE THREAD

**Issue by lmcadams2** [taers232c/GAM-Scripts3#1]
Hello,

I am getting an 'ERROR: Invalid argument' when I try and run step #4.  I am able to successfully run step #1 and create a list of all of my TeamDrives, but I get the error on step #4.

I am trying to get a list of TeamDrives to clean up empty ones and the old student folders.  Thank you for your time.

**Comment by taers232c** [comment]
Call me on Google Hangouts.

ross.scroggs@gmail.com
