### ISSUE TITLE
Script Use case Confusion

### ISSUE THREAD

**Issue by jamal-admin** [taers232c/GAM-Scripts3#14]
Hi,
Please can you help me determine the difference between GetSharedExternallyDriveACLs.py and GetNonDomainDriveACLs.py

Thanks

**Comment by taers232c** [comment]
There are doing the same thing but GetNonDomainDriveACLs.py let's you use regular expressions to define the domains ok interest.
This might be useful if your workspace contains many sub domains; e.g., sub1.domain.com, sub2.domain.com, ...

Ross
----
Ross Scroggs
***@***.***
