### ISSUE TITLE
GAM command for GetSharedExternallyDriveACLs.py

### ISSUE THREAD

**Issue by abusbykit** [taers232c/GAM-Scripts3#15]
I have ran the GAM command (gam all users print filelist id title permissions owners mimetype pm not domainlist mydomain.com > filelistperms.csv) and it takes all day to run it and when it's done the file is blank, with or without the domain clause.  Is there a way to run this and query a specific ou and it's sub ous and only active users?  Or do you have any idea why the file would be blank?

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation and I'll help.

Ross
----
Ross Scroggs
***@***.***

**Comment by abusbykit** [comment]
Thank you, I've emailed it to you.
