### ISSUE TITLE
Cyrillic characters are not displayed

### ISSUE THREAD

**Issue by xStevex** [taers232c/GAM-Scripts3#17]
When I run `gam all users print filelist id title permissions owners mimetype query "(visibility='domainCanFind' or visibility='domainWithLink')" > filelistperms.csv` it shows in csv all сyrillic names as "`Ã¢â•¨â•¢â•¨â”¤â•¨â•¡â•¨â•œâ•¨â••â•¤Ã`". 
How can it be fixed? As far as I understand, text encoding must be UTF-8.

**Comment by taers232c** [comment]
Try this: 
> gam redirect csv ./filelistperms.csv charset utf-8 all users print filelist id title permissions owners mimetype query "(visibility='domainCanFind' or visibility='domainWithLink')"
> 
> 
Are you on a Windows PC? If so, you can do: gam config charset utf-8 save
Now, all output will be in UTF-8; if you create input CSV files make sure they are in UTF-8.

Ross
----
Ross Scroggs
***@***.***

**Comment by xStevex** [comment]
Thanks!
