### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by bentran** [taers232c/GAM-Scripts3#2]
I'm trying this on a Windows host with Python 3.7 install and get the below error.

Steps:

Using GAMADV-XTD3

1) Run **gam redirect csv ./filelistperms.csv user testuser@domain.com print filelist id title permissions filepath** to get the filelistperms.csv file

2) I run **python GetPermissionsByPath.py filelistperms.csv pathperms.csv** to get the permisions and it spit out below errors:

```
C:\GAMADV-XTD>python GetPermissionsByPath.py filelistperms.csv pathperms.csv
Traceback (most recent call last):
  File "GetPermissionsByPath.py", line 60, in <module>
    for p in xrange(0, numPaths):
NameError: name 'xrange' is not defined
```

Not sure where the issue is.

Thanks

**Comment by taers232c** [comment]
Fixed
