### ISSUE TITLE
GetTeamDriveOrganizers.py

### ISSUE THREAD

**Issue by TommyShims** [taers232c/GAM-Scripts3#20]
Hi, I'm running this script and at step 5 it fails to find the ~Organizers header. Looking at the output of step 4, the TeamDriveOrganizers.csv has headers 'Owner', 'teamDriveId', 'teamDriveName', 'driveFileId', 'driveFileTitle', 'mimeType', 'permissionId', 'role', 'type', 'emailAddress', 'domain' instead of "id,name,organizers". 

Any help would be appreciated. Thanks!

**Comment by taers232c** [comment]
Send me a Meet/Zoom invitation and I'll help.

Ross
----
Ross Scroggs
***@***.***
