### ISSUE TITLE
I found no position to use the <select domain> feature with GetNonDomainFilterForwards.py

### ISSUE THREAD

**Issue by NoSubstitute** [taers232c/GAM-Scripts3#3]
https://github.com/taers232c/GAM-Scripts3/blob/master/GetNonDomainFilterForwards.py
I tried these places, and didn't find any others that were logical.

Original command
`gam config auto_batch_min 1 redirect csv ./filters.csv multiprocess all users print filters
`

My tries
```
gam select MyDomain config auto_batch_min 1 redirect csv ./filters.csv multiprocess all users print filters
gam config auto_batch_min 1 select MyDomain redirect csv ./filters.csv multiprocess all users print filters
gam config auto_batch_min 1 redirect csv ./filters.csv multiprocess select MyDomain all users print filters
```

They all failed while referring to a non-select oauth2.txt. Since my default oauth2.txt is blank, nothing happens, but error messages. The first position gave me many error messages, one for each user/thread/process, but the other two fail because of syntax.

**Comment by taers232c** [comment]
Kim,

> gam select MyDomain config auto_batch_min 1 redirect csv ./filters.csv multiprocess all users print filters

I'll call you in about an hour.

Ross
--
ross.scroggs@gmail.com
