### ISSUE TITLE
Error running GetSharedFilePermissions.py

### ISSUE THREAD

**Issue by seanism** [taers232c/GAM-Scripts3#8]
```
➜  IT git:(fix-deprovision) ✗ python3 GetSharedFilePermissions.py filePerms.csv deletePerms.csv
Traceback (most recent call last):
  File "GetSharedFilePermissions.py", line 70, in <module>
    outputCSV.writerow({'Owner': row['owners.0.emailAddress'],
KeyError: 'owners.0.emailAddress'
```

I get this error when trying to run the Python script.

**Comment by taers232c** [comment]
Sean,

Send me a Meet/Zoom invitation.

Ross
--
***@***.***

**Comment by seanism** [comment]
https://meet.google.com/egd-auqh-trt?pli=1

**Comment by seanism** [comment]
Alternatively https://us02web.zoom.us/j/86745553399?pwd=SGpVeWhMekhyWUU3UFBKWTZ5QjhVQT09

**Comment by seanism** [comment]
Resolved.  User error with mixing initial gam print command up with another script
